#=================================================
# Buddhini W. 01-27-2015
# Macro file myQweakCerenkovOnly.mac
# For simulating PMT DD effect
#
# Defaults to production LH2 simulation
#=================================================

#==========================
# Store Tracks
#==========================
/tracking/storeTrajectory 1

#==========================
# Cerenkov Detector related
#==========================
#  Air     :without Cerenkov light production 
#  Quartz  :with    Cerenkov light production
# 
# Angle is definedagaing vertical (y) axis
# - a tilt angle of 0.0*deg means vertical 
# - negative angle will tilt detector towards target

/Cerenkov/SetCerenkovMaterial Quartz

/Cerenkov/SetTiltingAngle           0.0 degree

/Cerenkov/SetPreradiatorMaterial PBA

# Define the number of Cereknov Bars
/Cerenkov/SetNumberOfDetectors 8

# Move Cerenkov Detectors to actual position 

/Cerenkov/Cerenkov1/SetCenterPositionInY  334.724 cm
/Cerenkov/Cerenkov1/SetCenterPositionInZ  576.665 cm

/Cerenkov/Cerenkov2/SetCenterPositionInY  334.742 cm
/Cerenkov/Cerenkov2/SetCenterPositionInZ  576.705 cm

/Cerenkov/Cerenkov3/SetCenterPositionInY  334.738 cm
/Cerenkov/Cerenkov3/SetCenterPositionInZ  577.020 cm

/Cerenkov/Cerenkov4/SetCenterPositionInY  335.036 cm
/Cerenkov/Cerenkov4/SetCenterPositionInZ  577.425 cm

/Cerenkov/Cerenkov5/SetCenterPositionInY  335.074 cm
/Cerenkov/Cerenkov5/SetCenterPositionInZ  577.515 cm

/Cerenkov/Cerenkov6/SetCenterPositionInY  335.252 cm
/Cerenkov/Cerenkov6/SetCenterPositionInZ  577.955 cm

/Cerenkov/Cerenkov7/SetCenterPositionInY  335.224 cm
/Cerenkov/Cerenkov7/SetCenterPositionInZ  577.885 cm

/Cerenkov/Cerenkov8/SetCenterPositionInY  334.888 cm
/Cerenkov/Cerenkov8/SetCenterPositionInZ  577.060 cm

# ELOG Detector/74: Positions of background detectors
#
# For practical reasons (MD9 is in the same octant as MD1) the background
# detector is here in the opposite octant than it actually was in (behind MD5).
#
# PRELIMINARY: More accurate numbers will require both the final survey
# and the local survey of the monument with respect to the detector itself.
#
# "Det. Origin" is (assumed to be) the center of the back of the bar, outer edge.
#
# Z position of Det. Origin = 737.86 cm
#   - 1 cm (half thickness) = 736.86 cm (Z in MC)
# X position of Det. Origin = 377.84 cm
#   - 9 cm (half width bar) = 368.84 cm (Y in MC)
# Y position of Det. Origin =  72.86 cm (X in MC)

#/Cerenkov/Cerenkov9/SetCenterPositionInX  -72.86 cm
#/Cerenkov/Cerenkov9/SetCenterPositionInY  368.84 cm
#/Cerenkov/Cerenkov9/SetCenterPositionInZ  736.86 cm

#====================================
# Event generator related
#====================================

# Usually this will be changed by a user macro that calls this 
# configuration macro.

# List of Generators (Included in src/QweakSimEPEvent.cc):
#  0 - Combination of all reactions
#  1 - LH2 elastic (default)
#  2 - Al elastic
#  3 - Al quasi-elastic (proton)
#  4 - Al quasi-elastic (neutron)
#  5 - LH2 inelastic (delta resonance)
#  6 - Moller scattering
#  7 - LH2 radiative lookup table (3.35 GeV)
#  8 - Al quasi-elastic, Bosted
#  88 - pion
#  9 - Al nuclear inelastics SPS
#  10 - Al GDR
#  11 - Al inelastic (Bosted)
#  12-17 - Al alloy (Zn, Mg, Cu, Cr, Fe, Si, respectively)

/EventGen/SelectReactionType    1

#==========================
# Octant Selection
#==========================
# Valid values range from 0 to 12
# default 0: events thrown in all octants
# 1-8: events thrown in corresponding octant
# 9-12: events thrown in two octants (9 for 1+5, 12 for 4+8)

#/EventGen/SelectOctant 11

#==========================
# Primary generator
#==========================
# If below set points are not given, the beam starts
# at (0,0,0) (inside QTOR)
#
/PrimaryEvent/SetBeamPositionX 0.0 cm
/PrimaryEvent/SetBeamPositionY 250.0 cm
/PrimaryEvent/SetBeamPositionZ 560.0 cm


#====================================
# Random Seed Handling
#====================================

# Inform the RunManager to systematically save the seed

/random/setSavingFlag 0

# Copy the following command line to your user macro and uncomment it 
# to use the seeds of the last event in last run
#/random/resetEngineFrom currentEvent.rndm
# Or use specific seeds from file 'myseed.rndm', for example 
#/random/resetEngineFrom myseed.rndm

