/MagneticField/SetTranslation 0.0 cm
/MagneticField/SetRotation -67.5 degree

/MagneticField/SetMinZ -250 cm
/MagneticField/SetMaxZ  250 cm
/MagneticField/SetStepZ 2 cm

/MagneticField/SetMinR 2 cm
/MagneticField/SetMaxR 300 cm
/MagneticField/SetStepR 2 cm

/MagneticField/SetMinPhi -0.5 degree
/MagneticField/SetMaxPhi 360.5 degree
/MagneticField/SetStepPhi 1 degree
/MagneticField/SetWrapPhi 2

/MagneticField/SetReferenceCurrent 8615.0
/MagneticField/ReadFieldMap peiqing_2007.dat
