%!PS-Adobe-3.0
%%BoundingBox: 24 24 588 768
%%Title: Enscript Output
%%For: Michael Gericke
%%Creator: GNU enscript 1.6.1
%%CreationDate: Fri Feb 25 10:09:57 2005
%%Orientation: Landscape
%%Pages: (atend)
%%DocumentMedia: Letter 612 792 0 () ()
%%DocumentNeededResources: (atend)
%%EndComments
%%BeginProlog
%%BeginResource: procset Enscript-Prolog 1.6 1
%
% Procedures.
%

/_S {	% save current state
  /_s save def
} def
/_R {	% restore from saved state
  _s restore
} def

/S {	% showpage protecting gstate
  gsave
  showpage
  grestore
} bind def

/MF {	% fontname newfontname -> -	make a new encoded font
  /newfontname exch def
  /fontname exch def

  /fontdict fontname findfont def
  /newfont fontdict maxlength dict def

  fontdict {
    exch
    dup /FID eq {
      % skip FID pair
      pop pop
    } {
      % copy to the new font dictionary
      exch newfont 3 1 roll put
    } ifelse
  } forall

  newfont /FontName newfontname put

  % insert only valid encoding vectors
  encoding_vector length 256 eq {
    newfont /Encoding encoding_vector put
  } if

  newfontname newfont definefont pop
} def

/SF { % fontname width height -> -	set a new font
  /height exch def
  /width exch def

  findfont
  [width 0 0 height 0 0] makefont setfont
} def

/SUF { % fontname width height -> -	set a new user font
  /height exch def
  /width exch def

  /F-gs-user-font MF
  /F-gs-user-font width height SF
} def

/M {moveto} bind def
/s {show} bind def

/Box {	% x y w h -> -			define box path
  /d_h exch def /d_w exch def /d_y exch def /d_x exch def
  d_x d_y  moveto
  d_w 0 rlineto
  0 d_h rlineto
  d_w neg 0 rlineto
  closepath
} def

/bgs {	% x y height blskip gray str -> -	show string with bg color
  /str exch def
  /gray exch def
  /blskip exch def
  /height exch def
  /y exch def
  /x exch def

  gsave
    x y blskip sub str stringwidth pop height Box
    gray setgray
    fill
  grestore
  x y M str s
} def

% Highlight bars.
/highlight_bars {	% nlines lineheight output_y_margin gray -> -
  gsave
    setgray
    /ymarg exch def
    /lineheight exch def
    /nlines exch def

    % This 2 is just a magic number to sync highlight lines to text.
    0 d_header_y ymarg sub 2 sub translate

    /cw d_output_w cols div def
    /nrows d_output_h ymarg 2 mul sub lineheight div cvi def

    % for each column
    0 1 cols 1 sub {
      cw mul /xp exch def

      % for each rows
      0 1 nrows 1 sub {
        /rn exch def
        rn lineheight mul neg /yp exch def
        rn nlines idiv 2 mod 0 eq {
	  % Draw highlight bar.  4 is just a magic indentation.
	  xp 4 add yp cw 8 sub lineheight neg Box fill
	} if
      } for
    } for

  grestore
} def

% Line highlight bar.
/line_highlight {	% x y width height gray -> -
  gsave
    /gray exch def
    Box gray setgray fill
  grestore
} def

% Column separator lines.
/column_lines {
  gsave
    .1 setlinewidth
    0 d_footer_h translate
    /cw d_output_w cols div def
    1 1 cols 1 sub {
      cw mul 0 moveto
      0 d_output_h rlineto stroke
    } for
  grestore
} def

% Column borders.
/column_borders {
  gsave
    .1 setlinewidth
    0 d_footer_h moveto
    0 d_output_h rlineto
    d_output_w 0 rlineto
    0 d_output_h neg rlineto
    closepath stroke
  grestore
} def

% Do the actual underlay drawing
/draw_underlay {
  ul_style 0 eq {
    ul_str true charpath stroke
  } {
    ul_str show
  } ifelse
} def

% Underlay
/underlay {	% - -> -
  gsave
    0 d_page_h translate
    d_page_h neg d_page_w atan rotate

    ul_gray setgray
    ul_font setfont
    /dw d_page_h dup mul d_page_w dup mul add sqrt def
    ul_str stringwidth pop dw exch sub 2 div ul_h_ptsize -2 div moveto
    draw_underlay
  grestore
} def

/user_underlay {	% - -> -
  gsave
    ul_x ul_y translate
    ul_angle rotate
    ul_gray setgray
    ul_font setfont
    0 0 ul_h_ptsize 2 div sub moveto
    draw_underlay
  grestore
} def

% Page prefeed
/page_prefeed {		% bool -> -
  statusdict /prefeed known {
    statusdict exch /prefeed exch put
  } {
    pop
  } ifelse
} def

% Wrapped line markers
/wrapped_line_mark {	% x y charwith charheight type -> -
  /type exch def
  /h exch def
  /w exch def
  /y exch def
  /x exch def

  type 2 eq {
    % Black boxes (like TeX does)
    gsave
      0 setlinewidth
      x w 4 div add y M
      0 h rlineto w 2 div 0 rlineto 0 h neg rlineto
      closepath fill
    grestore
  } {
    type 3 eq {
      % Small arrows
      gsave
        .2 setlinewidth
        x w 2 div add y h 2 div add M
        w 4 div 0 rlineto
        x w 4 div add y lineto stroke

        x w 4 div add w 8 div add y h 4 div add M
        x w 4 div add y lineto
	w 4 div h 8 div rlineto stroke
      grestore
    } {
      % do nothing
    } ifelse
  } ifelse
} def

% EPSF import.

/BeginEPSF {
  /b4_Inc_state save def    		% Save state for cleanup
  /dict_count countdictstack def	% Count objects on dict stack
  /op_count count 1 sub def		% Count objects on operand stack
  userdict begin
  /showpage { } def
  0 setgray 0 setlinecap
  1 setlinewidth 0 setlinejoin
  10 setmiterlimit [ ] 0 setdash newpath
  /languagelevel where {
    pop languagelevel
    1 ne {
      false setstrokeadjust false setoverprint
    } if
  } if
} bind def

/EndEPSF {
  count op_count sub { pos } repeat	% Clean up stacks
  countdictstack dict_count sub { end } repeat
  b4_Inc_state restore
} bind def

% Check PostScript language level.
/languagelevel where {
  pop /gs_languagelevel languagelevel def
} {
  /gs_languagelevel 1 def
} ifelse
%%EndResource
%%BeginResource: procset Enscript-Encoding-88591 1.6 1
/encoding_vector [
/.notdef      	/.notdef      	/.notdef      	/.notdef      	
/.notdef      	/.notdef      	/.notdef      	/.notdef      	
/.notdef      	/.notdef      	/.notdef      	/.notdef      	
/.notdef      	/.notdef      	/.notdef      	/.notdef      	
/.notdef      	/.notdef      	/.notdef      	/.notdef      	
/.notdef      	/.notdef      	/.notdef      	/.notdef      	
/.notdef      	/.notdef      	/.notdef      	/.notdef      	
/.notdef      	/.notdef      	/.notdef      	/.notdef      	
/space        	/exclam       	/quotedbl     	/numbersign   	
/dollar       	/percent      	/ampersand    	/quoteright   	
/parenleft    	/parenright   	/asterisk     	/plus         	
/comma        	/hyphen       	/period       	/slash        	
/zero         	/one          	/two          	/three        	
/four         	/five         	/six          	/seven        	
/eight        	/nine         	/colon        	/semicolon    	
/less         	/equal        	/greater      	/question     	
/at           	/A            	/B            	/C            	
/D            	/E            	/F            	/G            	
/H            	/I            	/J            	/K            	
/L            	/M            	/N            	/O            	
/P            	/Q            	/R            	/S            	
/T            	/U            	/V            	/W            	
/X            	/Y            	/Z            	/bracketleft  	
/backslash    	/bracketright 	/asciicircum  	/underscore   	
/quoteleft    	/a            	/b            	/c            	
/d            	/e            	/f            	/g            	
/h            	/i            	/j            	/k            	
/l            	/m            	/n            	/o            	
/p            	/q            	/r            	/s            	
/t            	/u            	/v            	/w            	
/x            	/y            	/z            	/braceleft    	
/bar          	/braceright   	/tilde        	/.notdef      	
/.notdef      	/.notdef      	/.notdef      	/.notdef      	
/.notdef      	/.notdef      	/.notdef      	/.notdef      	
/.notdef      	/.notdef      	/.notdef      	/.notdef      	
/.notdef      	/.notdef      	/.notdef      	/.notdef      	
/.notdef      	/.notdef      	/.notdef      	/.notdef      	
/.notdef      	/.notdef      	/.notdef      	/.notdef      	
/.notdef      	/.notdef      	/.notdef      	/.notdef      	
/.notdef      	/.notdef      	/.notdef      	/.notdef      	
/space        	/exclamdown   	/cent         	/sterling     	
/currency     	/yen          	/brokenbar    	/section      	
/dieresis     	/copyright    	/ordfeminine  	/guillemotleft	
/logicalnot   	/hyphen       	/registered   	/macron       	
/degree       	/plusminus    	/twosuperior  	/threesuperior	
/acute        	/mu           	/paragraph    	/bullet       	
/cedilla      	/onesuperior  	/ordmasculine 	/guillemotright	
/onequarter   	/onehalf      	/threequarters	/questiondown 	
/Agrave       	/Aacute       	/Acircumflex  	/Atilde       	
/Adieresis    	/Aring        	/AE           	/Ccedilla     	
/Egrave       	/Eacute       	/Ecircumflex  	/Edieresis    	
/Igrave       	/Iacute       	/Icircumflex  	/Idieresis    	
/Eth          	/Ntilde       	/Ograve       	/Oacute       	
/Ocircumflex  	/Otilde       	/Odieresis    	/multiply     	
/Oslash       	/Ugrave       	/Uacute       	/Ucircumflex  	
/Udieresis    	/Yacute       	/Thorn        	/germandbls   	
/agrave       	/aacute       	/acircumflex  	/atilde       	
/adieresis    	/aring        	/ae           	/ccedilla     	
/egrave       	/eacute       	/ecircumflex  	/edieresis    	
/igrave       	/iacute       	/icircumflex  	/idieresis    	
/eth          	/ntilde       	/ograve       	/oacute       	
/ocircumflex  	/otilde       	/odieresis    	/divide       	
/oslash       	/ugrave       	/uacute       	/ucircumflex  	
/udieresis    	/yacute       	/thorn        	/ydieresis    	
] def
%%EndResource
%%EndProlog
%%BeginSetup
%%IncludeResource: font Courier-Bold
%%IncludeResource: font Courier
/HFpt_w 10 def
/HFpt_h 10 def
/Courier-Bold /HF-gs-font MF
/HF /HF-gs-font findfont [HFpt_w 0 0 HFpt_h 0 0] makefont def
/Courier /F-gs-font MF
/F-gs-font 7 7 SF
/#copies 1 def
% Pagedevice definitions:
gs_languagelevel 1 gt {
  <<
    /PageSize [612 792] 
  >> setpagedevice
} if
%%BeginResource: procset Enscript-Header-enscript 1.6 1
%%IncludeResource: font Times-Bold
%%IncludeResource: font Times-Roman

% Fonts.
/Times-Bold /HeaderFont-Bold MF
/HeaderDateF /HeaderFont-Bold findfont 12 scalefont def

/Times-Roman /HeaderFont-Times MF
/HeaderHDRF /HeaderFont-Times findfont 14 scalefont def

/HeaderPageNumF /Helvetica-Bold findfont 28.8 scalefont def

/do_header {	% print enscript header
  gsave
    d_header_x d_header_y translate

    % light bar
    0 0 d_header_w d_header_h 2 div Box
    .95 setgray fill

    % dark gray boxes
    /dbw d_header_h 2 mul def	% dark box width
    /dbc .7 def			% dark box color

    % left dark box.
    0 0 dbw d_header_h Box
    dbc setgray fill

    0 setgray 
    HeaderDateF setfont
    moddatestr dup stringwidth pop dbw exch sub 2 div 
    d_header_h 2 div 2 add moveto show
    modtimestr dup stringwidth pop dbw exch sub 2 div 
    d_header_h 5 div moveto show

    % right dark box
    d_header_w dbw sub 0 dbw d_header_h Box
    dbc setgray fill

    HeaderPageNumF setfont
    1 setgray
    pagenumstr dup
    stringwidth pop dbw exch sub 2 div d_header_w dbw sub add
    d_header_h .2 mul moveto show

    % filename
    0 setgray 
    HeaderHDRF setfont
    d_header_w fname stringwidth pop sub 2 div d_header_h 8 div moveto
    fname show

    % user supplied header string.
    user_header_p {
      /h d_header_h 8 div 5 mul def

      % Implement strict enscript compatibility.
      user_header_center_str () eq user_header_right_str () eq and {
        d_header_w user_header_left_str stringwidth pop sub 2 div 
        h moveto user_header_left_str show
      } {
        dbw 5 add h moveto user_header_left_str show

        d_header_w user_header_center_str stringwidth pop sub 2 div 
        h moveto user_header_center_str show

	d_header_w dbw sub 5 sub user_header_right_str stringwidth pop
	sub h moveto user_header_right_str show
      } ifelse
    } if

  grestore
} def
%%EndResource
/d_page_w 744 def
/d_page_h 564 def
/d_header_x 0 def
/d_header_y 528 def
/d_header_w 744 def
/d_header_h 36 def
/d_footer_x 0 def
/d_footer_y 0 def
/d_footer_w 744 def
/d_footer_h 0 def
/d_output_w 744 def
/d_output_h 528 def
/cols 2 def
%%EndSetup
%%Page: (1) 1
%%BeginPageSetup
_S
90 rotate
24 -588 translate
/pagenum 1 def
/fname (Makefile) def
/fdir () def
/ftail (Makefile) def
% User defined strings:
/pagenumstr (1) def
/moddatestr (02/09/05) def
/modtimestr (16:08:52) def
/user_header_p false def
%%EndPageSetup
column_lines
column_borders
do_header
5 518 M
(# This is the make file to compile some useful classes for) s
5 510 M
(# data handling and visualization into a basic library.) s
5 502 M
(# The classes herein are derived from the ROOT data analysis) s
5 494 M
(# library.) s
5 478 M
(-include ../VERSION) s
5 462 M
(ROOT_INCLUDE  = $\(shell root-config --incdir\)) s
5 454 M
(PRG_INCLUDE   = ./include) s
5 446 M
(PRG_SOURCE    = ./source) s
5 430 M
(OBJECTS          = ) s
5 422 M
(NODICTOBJECTS    =) s
5 414 M
(# Here we list the object files that require a CINT dictionary.) s
5 406 M
(OBJECTS         += RDataContainer.o) s
5 398 M
(OBJECTS         += RDataWindow.o) s
5 390 M
(OBJECTS         += RDataFit.o) s
5 382 M
(OBJECTS         += RPlotList.o) s
5 374 M
(OBJECTS         += RDataFitEntry.o) s
5 366 M
(OBJECTS         += RProcessLog.o) s
5 358 M
(OBJECTS         += RComboBoxDialog.o) s
5 350 M
(OBJECTS         += RPlotContainer.o) s
5 342 M
(OBJECTS         += RNumberEntryDialog.o) s
5 334 M
(OBJECTS         += RStringEntryDialog.o) s
5 326 M
(# Now append the object files that Don't require a CINT dictionary.) s
5 318 M
(NODICTOBJECTS   += RVegas.o) s
5 302 M
(# Have this after all the object files are listed so that dictionaries) s
5 294 M
(# will be made automatically.) s
5 286 M
(DICTS           = $\(OBJECTS:.o=Dict.o\)) s
5 270 M
(APPLIC        = NPDGRootLib$\(VERS\).a) s
5 262 M
(MFILE         = Makefile) s
5 246 M
(OutPutOpt     = -o ) s
5 230 M
(# For Linux with egcs, gcc 2.9x, gcc 3.x \(>= RedHat 5.2\)) s
5 222 M
(# the correct flag settings for root are: ) s
5 206 M
(CXX           = g++) s
5 198 M
(CXXFLAGS      = -O -Wall -fPIC) s
5 190 M
(AR            = ar) s
5 182 M
(ARFLAGS       = -r) s
5 174 M
(LD            = g++) s
5 166 M
(LDFLAGS       = -O) s
5 158 M
(SOFLAGS       = -shared) s
5 150 M
(SYSLIBS       = ) s
5 134 M
(ROOTCFLAGS   := $\(shell root-config --cflags\)) s
5 126 M
(ROOTLIBS     := $\(shell root-config --libs\)) s
5 118 M
(ROOTGLIBS    := $\(shell root-config --glibs\)) s
5 102 M
(CXXFLAGS     += $\(ROOTCFLAGS\)) s
5 94 M
(LIBS          = $\(ROOTLIBS\) $\(SYSLIBS\)) s
5 86 M
(GLIBS         = $\(ROOTGLIBS\) $\(SYSLIBS\)) s
5 70 M
(ENSCRIPT        = @enscript -2Gjr -o) s
5 62 M
(#------------------------------------------------------------------------------------) s
5 38 M
(all: $\(APPLIC\)) s
5 22 M
($\(APPLIC\): $\(OBJECTS\) $\(NODICTOBJECTS\) $\(DICTS\)) s
5 14 M
(        $\(AR\) $\(ARFLAGS\) $\(APPLIC\) $^) s
5 6 M
(        $\(ENSCRIPT\) ./Documentation/$\(MFILE\).ps $\(MFILE\)) s
377 518 M
(        @echo "$@ done") s
377 502 M
(%.o : $\(PRG_SOURCE\)/%.cxx) s
377 494 M
(        $\(CXX\) -c $\(CXXFLAGS\) $< \\) s
377 486 M
(        -I$\(ROOT_INCLUDE\) -I$\(PRG_INCLUDE\)) s
377 470 M
(%Dict.o : %Dict.cxx) s
377 462 M
(        $\(CXX\) -c $\(CXXFLAGS\) $< \\) s
377 454 M
(         -I$\(ROOT_INCLUDE\) -I$\(PRG_INCLUDE\)) s
377 438 M
(%Dict.cxx : $\(PRG_INCLUDE\)/%.h) s
377 430 M
(        @echo "Generating dictionary $@...") s
377 422 M
(        @rootcint -f $@ -c $^) s
377 398 M
(clean:) s
377 390 M
(        rm -f ./*.o ./core ./*~ $\(PRG_SOURCE\)/*~ $\(PRG_INCLUDE\)/*~ \\) s
377 382 M
(        ./*Dict.cxx ./*Dict.h ./~* ./G__*.*) s
377 366 M
(Documentation/%.cxx.ps :: $\(PRG_SOURCE\)/%.cxx) s
377 358 M
(        $\(ENSCRIPT\) $@ $<) s
377 350 M
(Documentation/%.h.ps :: $\(PRG_INCLUDE\)/%.h) s
377 342 M
(        $\(ENSCRIPT\) $@ $<) s
377 326 M
(docu: $\(patsubst %.o,Documentation/%.cxx.ps, $\(OBJECTS\) $\(NODICTOBJECTS\)\) \\) s
377 318 M
(        $\(patsubst %.o,Documentation/%.h.ps, $\(OBJECTS\) $\(NODICTOBJECTS\)\) \\) s
377 310 M
(        $\(patsubst $\(PRG_INCLUDE\)/%Def.h,Documentation/%Def.h.ps,\\) s
377 302 M
(                $\(wildcard $\(PRG_INCLUDE\)/*Def.h\) \)) s
_R
S
%%Trailer
%%Pages: 1
%%DocumentNeededResources: font Times-Roman Courier-Bold Courier 
%%+ font Times-Bold 
%%EOF
